# Generated by Django 3.2.9 on 2022-12-11 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.CharField(max_length=100, verbose_name='Total')),
                ('products', models.JSONField(blank=True, null=True, verbose_name='List Articles (JSON)')),
                ('name', models.CharField(max_length=255, verbose_name='client name')),
            ],
        ),
    ]
