# Generated by Django 4.0.3 on 2022-04-09 08:10

from django.db import migrations, models
import django.db.models.deletion
import owner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='shoes name')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('price', models.CharField(max_length=255, verbose_name='price')),
                ('cover', models.FileField(blank=True, upload_to='')),
                ('owner', models.ForeignKey(default=owner.models.Owner.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='owner_shoes', to='owner.owner', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'INFO ',
                'verbose_name_plural': 'INFOS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoesPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='shoes/images/', verbose_name='Photos')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoesinfo')),
            ],
            options={
                'verbose_name': 'SHOES PHOTO ',
                'verbose_name_plural': ' PHOTOS',
            },
        ),
    ]
