# Generated by Django 4.0.3 on 2022-04-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesinfo',
            name='cover',
            field=models.ImageField(blank=True, upload_to='shoes/images/'),
        ),
    ]
