# Generated by Django 4.0.3 on 2022-04-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_shoesinfo_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoesinfo',
            old_name='cover',
            new_name='cover_shoes',
        ),
    ]
