# Generated by Django 4.0.3 on 2022-04-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_rename_cover_shoesinfo_cover_shoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoesinfo',
            name='cover_shoes',
        ),
        migrations.AddField(
            model_name='shoesinfo',
            name='cover',
            field=models.FileField(blank=True, upload_to='shoes/images/'),
        ),
    ]
