# Generated by Django 4.0.3 on 2022-04-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_remove_shoesinfo_cover_shoes_shoesinfo_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesinfo',
            name='cover',
            field=models.FileField(upload_to='shoes/images/'),
        ),
    ]
