# Generated by Django 4.0.3 on 2022-04-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Shop name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Shop ',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('name', models.CharField(max_length=512, verbose_name='username')),
                ('telephone', models.CharField(max_length=30, unique=True, verbose_name='tel')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('is_active', models.BooleanField(default=False, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date of modification')),
                ('is_owner_shop', models.BooleanField(default=True, verbose_name='Store owner')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='admin')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='owner.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'owner ',
                'verbose_name_plural': 'Owners',
            },
        ),
    ]
