# Generated by Django 4.0.3 on 2022-04-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='username')),
                ('telephone', models.CharField(max_length=30, verbose_name='tel')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('is_active', models.BooleanField(default=False, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date of modification')),
            ],
            options={
                'verbose_name': 'Client ',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
